
language: node_js
node_js:
  - "9"

addons:
  chrome: stable
cache:
  directories:
    - $HOME/cypress
    - "node_modules"

before_script:
  - npm start &
script:
  - npm i cypress
  - npm t -- run

before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN

    skip_cleanup: true
    on:
      master: true
