
language: node_js
node_js:
  - "9"

addons:
  chrome: stable
cache:
  directories:
    - $HOME/cypress
    - $HOME/.cache

before_script:
  - npm install -g wait-on
  - npm start &
  - wait-on http://localhost:8000
script:
  - npm i cypress --no-save
  - npm t -- run

before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN

    skip_cleanup: true
    on:
      master: true
